name: guard-secrets
on:
  pull_request:
    branches: [ main ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Block committed secret files
        run: |
          set -e
          CHANGED=$(git diff --name-only origin/main...HEAD || true)
          echo "$CHANGED" | grep -E '(^|/)(\.env(\.|$)|\.git-credentials$|\.netrc$|\.npmrc$)' && { echo "❌ Secret-like file detected"; exit 1; } || echo "✅ No direct secret files"
      - name: Require templates present
        run: |
          test -f .env.example || { echo "❌ .env.example missing"; exit 1; }
          # dotenv-vault encrypted bundle must remain tracked
          test -f .env.vault || { echo "❌ .env.vault missing"; exit 1; }
      - name: Type-check (no emit)
        run: |
          if [ -f tsconfig.json ]; then npm i -g typescript && tsc --noEmit; else echo "No TS, skipping"; fi
